In [1]:
import numpy as np

In [25]:
from cvxopt import matrix, solvers

In [2]:
from sklearn import svm

In [5]:
dir(clf)

['C',
 '__abstractmethods__',
 '__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__setstate__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_abc_cache',
 '_abc_negative_cache',
 '_abc_negative_cache_version',
 '_abc_registry',
 '_check_proba',
 '_compute_kernel',
 '_decision_function',
 '_dense_decision_function',
 '_dense_fit',
 '_dense_predict',
 '_dense_predict_proba',
 '_estimator_type',
 '_get_coef',
 '_get_param_names',
 '_impl',
 '_pairwise',
 '_predict_log_proba',
 '_predict_proba',
 '_sparse_decision_function',
 '_sparse_fit',
 '_sparse_kernels',
 '_sparse_predict',
 '_sparse_predict_proba',
 '_validate_for_predict',
 '_validate_targets',
 '_warn_from_fit_status',
 'cache_size',
 'class

In [3]:
clf = svm.SVC()

In [6]:
X = [[0, 0], [1, 1]]
y = [0, 1]

In [7]:
clf.fit(X,y)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [188]:
def load_CSV(file_name):
    tmp = np.loadtxt(file_name, dtype=np.str, delimiter=",")
    features = tmp[1:,:-1].astype(np.float)# load features
    labels = tmp[1:,-1].astype(np.float)# load labels
    return features, labels # return ndarray

In [189]:
X,Y = load_CSV('creditCard.csv')

In [190]:
Y = np.array([-1 if y==0 else y for y in Y])

In [121]:
q = matrix([-1. for i in range(n)])
G = matrix(-np.eye(n))
h = matrix(np.zeros((n,1)))
A = matrix(Y).trans()
b = matrix(0.)

sol = solvers.qp(P, q, G, h, A, b)

     pcost       dcost       gap    pres   dres
 0: -6.7749e+02 -2.2276e+03  1e+04  1e+02  3e+00
 1: -3.3606e+03 -8.4826e+03  1e+04  9e+01  3e+00
 2: -7.9622e+03 -1.6570e+04  1e+04  7e+01  2e+00
 3: -2.0497e+04 -2.7214e+04  7e+03  5e+01  1e+00
 4: -8.4496e+04 -9.2098e+04  8e+03  4e+01  1e+00
 5: -8.8768e+05 -9.0554e+05  2e+04  4e+01  1e+00
 6: -2.5074e+07 -2.5308e+07  2e+05  4e+01  1e+00
 7: -8.5109e+08 -8.5661e+08  6e+06  4e+01  1e+00
 8: -8.5958e+08 -8.6515e+08  6e+06  4e+01  1e+00
 9: -8.7097e+08 -8.7660e+08  6e+06  4e+01  1e+00
10: -1.0923e+09 -1.0993e+09  7e+06  4e+01  1e+00
11: -1.2861e+09 -1.2942e+09  8e+06  4e+01  1e+00
12: -1.4510e+09 -1.4600e+09  9e+06  4e+01  1e+00
Terminated (singular KKT matrix).


In [134]:
np.array(w).shape

(1319, 1)

In [133]:
Y.reshape(-1,1).shape

(1319, 1)

In [137]:
X.shape

(1319, 9)

In [163]:
((np.array(w) * Y.reshape(-1, 1)).T @ X).shape

(1, 9)

In [152]:
np.where(Y==1)

(array([   0,    1,    2, ..., 1316, 1317, 1318]),)

In [157]:
X

array([[  0.     ,  37.66667,   4.52   , ...,  54.     ,   1.     ,  12.     ],
       [  0.     ,  33.25   ,   2.42   , ...,  34.     ,   1.     ,  13.     ],
       [  0.     ,  33.66667,   4.5    , ...,  58.     ,   1.     ,   5.     ],
       ..., 
       [  0.     ,  40.58333,   4.6    , ...,   1.     ,   1.     ,   2.     ],
       [  0.     ,  32.83333,   3.7    , ...,  60.     ,   1.     ,   7.     ],
       [  0.     ,  48.25   ,   3.7    , ...,   2.     ,   1.     ,   0.     ]])

In [179]:
X[Y==1] @ w.T

array([[-0.00188098],
       [-0.00026475],
       [-0.00124469],
       ..., 
       [-0.00206443],
       [ 0.00037625],
       [-0.00186364]])

In [245]:
a=np.min(X[Y==1] @ w.T)
a

-0.0041466994714351143

In [246]:
b=np.max(X[Y==-1] @ w.T)
b

0.0034321141277943636

In [263]:
b=-(a+b)/2

In [183]:
1-a

1.0041466994714352

In [215]:
np.array(P).mean()

1285.2468474092382

In [238]:
np.array(A)

array([[ 1.,  1.,  1., ...,  1.,  1.,  1.]])

In [230]:
a.T @ Y.reshape(-1, 1)

array([[ -1.26892701e-07]])

In [224]:
np.array([[(kernel(X[i],X[j]) * Y[i]*Y[j]) for i in range(n//300)] for j in range(n//300)])

array([[ 4510.20842889,  3265.3551775 ,  4494.45134889,  2595.314235  ],
       [ 3265.3551775 ,  2446.4189    ,  3180.3067775 ,  1962.2718    ],
       [ 4494.45134889,  3180.3067775 ,  4560.69466889,  2524.263435  ],
       [ 2595.314235  ,  1962.2718    ,  2524.263435  ,  1611.7016    ]])

In [288]:
class SVC():
    def __init__(self, kernel=None):
        if kernel == None:
            self.kernel = lambda x,z : np.dot(x,z)
        else:
            self.kernel = kernel
           
    def train(self, X, Y):
        n = len(Y)
        P = matrix([[(self.kernel(X[i],X[j]) * Y[i]*Y[j]) for i in range(n)] for j in range(n)])
        q = matrix([-1. for i in range(n)])
        G = matrix(-np.eye(n))
        h = matrix(np.zeros((n,1)))
        A = matrix(Y).trans()
        b = matrix(0.)
        sol = solvers.qp(P, q, G, h, A, b)
        
        self.w = (np.array(sol['x']) * Y.reshape(-1, 1)).T @ X
        self.b = - ( np.min(X[Y==1] @ w.T) + np.max(X[Y==-1] @ w.T) )/2
        
    def predict(self, X):
        scores = X @ self.w.T + self.b
        return [1 if score>0 else -1 for score in scores]

In [285]:
score = X @ w.T + b

In [286]:
score.shape

(1319, 1)

In [290]:
mysvc=SVC()

In [291]:
mysvc.train(X,Y)

     pcost       dcost       gap    pres   dres
 0: -6.7749e+02 -2.2276e+03  1e+04  1e+02  3e+00
 1: -3.3606e+03 -8.4826e+03  1e+04  9e+01  3e+00
 2: -7.9622e+03 -1.6570e+04  1e+04  7e+01  2e+00
 3: -2.0497e+04 -2.7214e+04  7e+03  5e+01  1e+00
 4: -8.4496e+04 -9.2098e+04  8e+03  4e+01  1e+00
 5: -8.8768e+05 -9.0554e+05  2e+04  4e+01  1e+00
 6: -2.5074e+07 -2.5308e+07  2e+05  4e+01  1e+00
 7: -8.5109e+08 -8.5661e+08  6e+06  4e+01  1e+00
 8: -8.5958e+08 -8.6515e+08  6e+06  4e+01  1e+00
 9: -8.7097e+08 -8.7660e+08  6e+06  4e+01  1e+00
10: -1.0923e+09 -1.0993e+09  7e+06  4e+01  1e+00
11: -1.2861e+09 -1.2942e+09  8e+06  4e+01  1e+00
12: -1.4510e+09 -1.4600e+09  9e+06  4e+01  1e+00
Terminated (singular KKT matrix).


In [292]:
mysvc.predict(X)

[-1,
 1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 1,
 -1,
 -1,
 -1,
 -1,
 1,
 -1,
 -1,
 -1,
 1,
 -1,
 -1,
 -1,
 -1,
 -1,
 1,
 -1,
 -1,
 -1,
 -1,
 -1,
 1,
 -1,
 -1,
 1,
 -1,
 1,
 1,
 -1,
 1,
 -1,
 -1,
 -1,
 -1,
 1,
 1,
 1,
 1,
 -1,
 -1,
 1,
 -1,
 -1,
 -1,
 1,
 1,
 -1,
 -1,
 -1,
 -1,
 -1,
 1,
 -1,
 -1,
 1,
 -1,
 -1,
 -1,
 -1,
 1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 1,
 -1,
 -1,
 1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 1,
 -1,
 -1,
 1,
 1,
 -1,
 1,
 -1,
 1,
 1,
 1,
 1,
 -1,
 -1,
 1,
 -1,
 -1,
 -1,
 1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 1,
 -1,
 -1,
 -1,
 1,
 1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 1,
 1,
 1,
 -1,
 -1,
 1,
 1,
 -1,
 -1,
 -1,
 -1,
 -1,
 